substitutions:
  _PROJECT: ""
  _REGISTRY: asia-southeast2-docker.pkg.dev
  _REPO: tring-service
  _TAG: latest

steps:
  - name: "gcr.io/cloud-builders/docker"
    id: build-pipeline
    args:
      - build
      - -t
      - ${_REGISTRY}/${_PROJECT}/${_REPO}/pipeline:${_TAG}
      - .

  - name: "gcr.io/cloud-builders/docker"
    id: push-pipeline
    args: ["push", "${_REGISTRY}/${_PROJECT}/${_REPO}/pipeline:${_TAG}"]
    waitFor: ["build-pipeline"]

options:
  logging: CLOUD_LOGGING_ONLY
